#❶ Docker Compose Syntax версия
version: "3.8"
#❷ Раздел, содержащий все контейнеры для запуска
services:

  # Applications

  #❸ Раздел, описывающий контейнер catalog-service
  catalog-service:
    #❹ Служба каталогов должна запускаться после базы данных PostgreSQL
    depends_on:
      - polar-postgres
    #❺ Образ, используемый для запуска контейнера
    image: "catalog-service"
    #❻ Имя контейнера
    container_name: "catalog-service"
    #❼ Раздел со списком сопоставлений портов
    ports:
      - "9001:9001"
        #❶ Порт, на котором JVM будет прослушивать отладочные соединения.
      - "8001:8001"
    #❽ В Этом разделе перечислены переменные среды
    environment:
      #❾ Переменная среды Paketo Buildpacks для настройки количества потоков для расчета памяти
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      #❷ Активирует конфигурацию JVM для приема отладочных соединений (предоставляется Buildpacks).
      - BPL_DEBUG_ENABLED=true
      #❸ Отладочные соединения принимаются через сокет на порту 8001 (предоставляется Buildpacks).
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_PORT=8001
#      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      #❿ Включает пружинный профиль «TestData»
      - SPRING_PROFILES_ACTIVE=testdata
    networks:
      catalog-network:
        aliases:
          - "catalog-service"

#  config-service:
#    image: "config-service"
#    container_name: "config-service"
#    ports:
#      - 8888:8888
#      - 9888:9888
#    environment:
#      # Buildpacks environment variable to configure the number of threads in memory calculation
#      - BPL_JVM_THREAD_COUNT=50
#      # Buildpacks environment variable to enable debug through a socket on port 9888
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=9888

  # Backing Services

  #⓫ Раздел, описывающий контейнер Polar-postgres.
  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
    networks:
      catalog-network:
        aliases:
          - "polar-postgres"

networks:
  catalog-network:
    driver: bridge